AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Parameters:
  UnleashToken:
    Type: String

Resources:
  SentimentFunction:
    Type: AWS::Serverless::Function
    Auth:
      Authorizer: NONE
    Properties:
      CodeUri: lambda/
      Handler: app.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.8
      Timeout: 10
      Environment:
        Variables:
          UnleashToken: !Ref UnleashToken

      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /sentiment
            Method: post

  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: default
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'logs:*'
                Resource: '*'
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 'comprehend:*'
                Resource: '*'

Outputs:
  SentimentAPI:
    Description: "API Gateway endpoint URL for Prod stage for Sentiment function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sentiment/"
  SentimentFunction:
    Description: "Sentiment Lambda Function ARN"
    Value: !GetAtt SentimentFunction.Arn
  SentimentFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaRole.Arn